export { default as BannerImg } from './banner.png';
export { default as EmptyIcon } from './emptyIcon.svg';
// export { default as FaceSticker } from './face_sticker.png';
export { default as HomeLogo } from './homeLogo.svg';
export { default as ImgShareCapture } from './ImgShareCapture.png';
// export { default as LoginBanner } from './ImgSignUpBanner.svg';
export { default as Logo } from './logo.svg';
export { default as PictureId1 } from './pictureId1.png';
export { default as PictureId2 } from './pictureid2.png';
export { default as PlayerTitle } from './PlayerTitle.png';
export { default as StickerTest } from './stickerTest.png';
