nodeLinker: 'pnp'

packageExtensions:
  'your-package@*':
    dependencies:
      moduleName: 'portal:./src'
  styled-components@*:
    dependencies:
      react-is: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.3.1.cjs
