export { ReactComponent as IcClose } from './ic_close.svg';
export { ReactComponent as IcCropImg } from './ic_cropImg.svg';
export { ReactComponent as IcHand } from './ic_hand.svg';
export { ReactComponent as IcImageAdd } from './ic_imageAdd.svg';
export { ReactComponent as IcModify } from './ic_modify.svg';
export { ReactComponent as IcMoveCrop } from './ic_moveCrop.svg';
export { ReactComponent as IcRemoveImg } from './ic_removeImg.svg';
export { ReactComponent as IcGoback } from './IcGoback.svg';
export { ReactComponent as IcPickmeSticker } from './picme_sticker.svg';
